/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.pokeTeams;

import com.fcm.pokeTeams.enums.VistasControladores;
import com.fcm.pokeTeams.util.CargadorFXML;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.stage.Stage;

public class Main extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage ventana) throws Exception {
        CargadorFXML.getInstance().cargar(VistasControladores.LOGIN, ventana);
        ventana.show();
    }

}
