/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.pokeTeams;

import com.fcm.pokeTeams.enums.VistasControladores;
import com.fcm.pokeTeams.util.CargadorFXML;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Insets;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/**
 * Plantilla JAVAFX
 * Autor:
 * Curso y año:
 * Objetivo de esta clase:
 */
public class Main extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage ventana) throws Exception {
        CargadorFXML.getInstance().cargar(VistasControladores.LOGIN, ventana);
        /*Parent root = FXMLLoader.load(getClass().getResource("/fxml/logIn.fxml"));
        
        Scene scene=new Scene(root);
        Stage escenaPrincipal = primaryStage;
        escenaPrincipal.setScene(scene);
        escenaPrincipal.setTitle("Log In");
        escenaPrincipal.getIcons().add(new Image("/img/Pokeball.png"));*/
        ventana.setUserData("Hola");
        ventana.show();
    }

}
