/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.pokeTeams;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       Mainp classUnderTest = newMainp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
